### ISSUE TITLE
There are 9 columns in acs_mo now - used to be 10

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/courtbot#115]
Less columns is messing up loader in acs_mo csv

**Comment by brendanbabb** [comment]
Additional info from Sharon:

------------------------------------

If Code for Anchorage will write a more robust data loader, let me introduce you to three new data sets to replace the ones you used before.

 

https://public.courts.alaska.gov/web/majic/sandbox/acs_mo_cr_case_most_recent_event_1705.csv  

https://public.courts.alaska.gov/web/majic/sandbox/acs_mo_cr_case_most_recent_event_0645_addon.csv

https://public.courts.alaska.gov/web/majic/sandbox/acs_mo_cr_case_most_recent_event_1145_addon.csv

 

By the file name, you can tell they all include minor offense and criminal cases.  The numbers represent the military hours when the snapshot is taken.   Addon files populate the “is_add_on” flag to show which events are newer since the 1705 hour (5:05pm) the day before, and yet contain the complete set of all future events for criminal and minor offense cases.  The “is_add_on” flag in the 1705 file will always be false. 

 

All three files can be used independent of each other.   Column headers are self-explanatory. 

 

I think you will find these three new data sets more valuable.

**Comment by mark-meyer** [comment]
@brendanbabb When I download `acs_mo_event.csv` I still 10 columns:

`"event_dt","last_name","first_name","address","crtroom","start_tm","ticket_nbr","actn_code","actn_description","pay_now"`

The `pay_now` column seem to always be empty, but the lines all end with a comma which makes one more empty column in the data.

**Comment by brendanbabb** [comment]
This has been fixed
