### ISSUE TITLE
Run tests in a different database

### ISSUE THREAD

**Issue by tescher** [codeforanchorage/courtbot#18]
Make sure Heroku doesn't blow away the production database during deployment (does it run tests, what database does it use?)

**Comment by markmeyerphoto** [comment]
#52 

Here's an idea for this. Basically it adds a connections module that lets you define more than one DB connection. The app can then pick which of those to use based on NODE_ENV. The test script set NODE_ENV to 'test' which then uses the test db setup in the file. This will allow separate test/development/production databases and should default to development. The tests now run without nuking the development db, which is convenient. It does require adding the test database - I updated the README with the additional step.
