### ISSUE TITLE
First search for a citation number after load.js runs seems to not find the case

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/courtbot#22]
I have experienced this 4 times. I run  runners/load.js and get new data and then when I look for a case I know is in there I get a can't find your case message, but then if I submit the citation again, it finds it.

Not sure what is causing this and I will try to replicate a few more times.

**Comment by brendanbabb** [comment]
Tried it a couple times and it appears to be working. Closing ticket.

**Comment by tescher** [comment]
Database not being written right away? Wonder if there is a way to force a
sync

Tim Escher
tim@eschers.com
608 432 5799

**Comment by btrott18** [comment]
Wondering if the issue is related to updating dependencies/versions?

Does the build job run an npm update before executing tasks?

**Comment by btrott18** [comment]
Nevermind.  Looks like a fresh install...  I may need to retest using all
the same versioning as the build job.
