### ISSUE TITLE
Error when the sendReminders.js runs and no reminders are in the database

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/courtbot#23]
Not a critical error, because it runs fine when there are reminders in the database.  Just to clean up the logs if there are no reminders.

C:\Users\ecbjb\Documents\GitHub\courtbot [master ≡]> heroku run node runners/sendReminders.js --app courtbot-anc2-test
Running node runners/sendReminders.js on courtbot-anc2-test... up, run.7540 (Free)
Knex:warning - knex.initialize is deprecated, pass your config object directly to the knex module
{ [error: select \* from "reminders" inner join "cases" on "reminders"."case_id" = "cases"."id" where "sent" = $1 and ("cases"."date" + interval '8 hours') < (now() + interval '24 hours') - relation "reminders" does not exist]
 name: 'error',
 length: 101,
 severity: 'ERROR',
 code: '42P01',
 detail: undefined,
 hint: undefined,
 position: '15',
 internalPosition: undefined,
 internalQuery: undefined,
 where: undefined,
 file: 'parse_relation.c',
 line: '1159',
 routine: 'parserOpenTable' }
C:\Users\ecbjb\Documents\GitHub\courtbot [master ≡]>

**Comment by robbiepc30** [comment]
@brendanbabb was this fixed awhile ago? I cannot recreate this problem.  I have cleared the reminders table and I am not able to recreate this issue. Does this happen if there are no cases for that day?

My results when running the same with the sendReminders table cleared out;

`heroku run node runners/sendReminders.js
Running node runners/sendReminders.js on ⬢ courtbot-anc2-test... up, run.4386 (Free)
{ [Error: ENOENT, no such file or directory '.env'] errno: 34, code: 'ENOENT', path: '.env', syscall: 'open' }
Date: 2017-03-29 Offset: -08:00
Date: 2017-03-29 Offset: -08:00
DAT 2017-03-31T08:00:49Z
Success:  []`

**Comment by mfrederickson** [comment]
@brendanbabb I was not able to reproduce the problem either.  Though it looks like the error you received was because the reminders table had not been created.
```
 relation "reminders" does not exist
```

However, I do get the same NOENT error as @robbiepc30 though even after I ran the `touch .env` command as mentioned in the README...
