### ISSUE TITLE
Trim leading and trailing spaces of Citation number before querying

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/courtbot#28]
I was pasting a citation number and accidentally had a leading space and it didn't find the case. We should trim the spaces before and after the citation number before querying.

**Comment by simonv3** [comment]
This looks like it's been fixed?

**Comment by ragingsmurf** [comment]
Am new to the Repo, but it looks like this is taken care of here: https://github.com/codeforanchorage/courtbot/blob/master/db.js#L9

If so, can we close this issue?
