### ISSUE TITLE
Save citations as jsonb instead of plain json

### ISSUE THREAD

**Issue by markmeyerphoto** [codeforanchorage/courtbot#54]
Postrgres has a binary JSON type that is almost identical to the old JSON type but with some important advantages. The postgres docs say:
> In general, most applications should prefer to store JSON data as jsonb, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys.

It's more efficient and compact. But the real benefit is that it supports indexing natively and it natively supports containment operators, which the current code is mimicking with  custom function and GIN index. 

Changing to jsonb will make the SQL queries less byzantine and more readable. For example instead of:

    knex.raw(`'{"${citation}"}'::text[] <@ (json_val_arr(citations, 'id'))`);

which requires the custom function `json_val_arr` on the db,  we can have:

    knex.raw(`citations @> '[{"id": "${citation}"}]' `);

Which translates to:

    SELECT * FROM cases WHERE citations @> '[{"id": "PALZE000001650017"}]';

Unlike the first query, this query is well-documented and relatively intuitive to understand, which is nice for a project with different people working.

The change doesn't require much in the code: just a few lines to change the table setup in manager.js and the queries in db.js. I don't know what would be required, however, on any deployed versions where we would need to change a column type on an existing db.

**Comment by mfrederickson** [comment]
Sounds like that's the way to go. Would a simple export/backup of the table's data and then reloading it after the table is recreated work?

**Comment by markmeyerphoto** [comment]
Thanks @mfrederickson - We rolled this change into the simplePromises branch yesterday, so if you use the updated branch you'll need to re-create (or otherwise convert) your `cases` and `reminders` tables. The updated column types let us use the simpler queries in db.js avoid using `knex.raw()` which should be safer with user-supplied info.

**Comment by markmeyerphoto** [comment]
#65 Addressed this.
