### ISSUE TITLE
Update Twilio Library

### ISSUE THREAD

**Issue by mark-meyer** [codeforanchorage/courtbot#66]
We are currently using Twilio's version 1.6 library. The current version is 3.6.7 and the 2.x branch was officially deprecated in August. 

The new version is a fairly easy update but because of the way some of the test are written, they are hard to fix. The current tests use Nock to intercept Twilio's request and test that the body of the POST is correct. This creates a dependency on Twilio's implementation which is not under our control (or being tested). 

I would like to change the test method to instead stub the Twilio' `sendMessage()` function and test that are calling that with the correct information. This would assume that `sendMessage()` will do what it's supposed to, but I *think* we can trust that. This would allow the test to be independent of Twilio's implementation in the future, which should make it much easier to stay up-to-date. Does anyone see any problems with this?

**Comment by brendanbabb** [comment]
Sounds good to me

**Comment by mark-meyer** [comment]
We are now on 3.19.
