### ISSUE TITLE
Fix security issues flagged by github

### ISSUE THREAD

**Issue by tescher** [codeforanchorage/courtbot#77]
If someone wants to fix the security issues flagged by Github in the bus-sms and courtbot repos, let me know and I'll add you as an admin to the repo so you can see the issues, fix them, and then make sure the flags go away.

**Comment by mfrederickson** [comment]
I'd be willing to try my hand at these for courtbot if you're ok with that.

**Comment by brendanbabb** [comment]
@mfrederickson We are going to try and do a promotional push on CourtBot Saturday as part of National Day of Civic Hacking. If you want to check on the security issues that would be great and we can factor in when to merge them in coordination with the attention to the site.

**Comment by brendanbabb** [comment]
@mfrederickson I added you as an admin to view the security info.

**Comment by mfrederickson** [comment]
I don't see any security issues listed anywhere.

So, according to [this help article](https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/) I can enable the security/vulnerability check in the settings for the repo-- which is currently unchecked-- if that's so, how can @tescher see them?

And [here](https://help.github.com/articles/choosing-the-delivery-method-for-your-notifications/#choosing-the-delivery-method-for-security-alerts-for-vulnerable-dependencies) it talks about setting up the dependency graph under insights to be able to see them.

What do I need to do to be able to see them and where should I be looking? Or will they become visible after some GitHub nightly process runs?

**Comment by brendanbabb** [comment]
Good questions. I just enabled the box to be checked and am not seeing any warnings. I see them on the realtime bus repo. Maybe it is an overnight thing or with the new changes to courtbot it is all fixed?
